name = "iamani"
pages_build_output_dir = "dist"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "iamanidata"
database_id = "052b6fb1-af0c-408c-bc24-0ddbb595246f"